spring.application.name=ohseatback
spring.config.import=optional:file:.env[.properties],optional:file:ohseatback/.env[.properties]

server.port=8000

# MariaDB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# mybatis
mybatis.mapper-locations=classpath:database/mapper/api/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# RECAPTCHA
recaptcha.secret-key=${RECAPTCHA_KEY}

# securityLog
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# kakaoAPI
kakao.api.key=${KAKAO_API_KEY}

# boxofficeAPI
kobis.api.key=${KOBIS_KEY}
tmdb.api.key=${TMDB_KEY}

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
